### ISSUE TITLE
I am having trouble getting graphics to function

### ISSUE THREAD

**Issue by Sirvant** [JasonTitcomb/Discriminator#17]
I tried sending a report that just opens a browser, and create support issue leads me here indirectly.  I do not necessarily want to post my g-code publicly but would happily send it to you as long as it is not posted publicly.

My code runs on our haas graphics page with no problems, and we are wanting to use discriminator to test our code vs the machine..

Code is turning code.

Can chat on whats app/signal/telegram/discord if you want real time comunication.

Get these errors
at MacGen.FANUC_Parser.Parse(String gcode, String fileName)
   at MacGen.MG_ParserEvaluator.Parse(String gcode, String fileName)
   at MacGen.clsParser.ProcessText(String sFileName, String sFileContents, List`1 gfxRecs, List`1& prgs, BackgroundWorker worker)
   at MacGen.frmBasicViewer.BGW_DoWork(Object sender, DoWorkEventArgs e) in D:\Dev\Discrim.NET\Discrim.NET\frmBasicViewer.vb:line 306

   at System.Windows.Forms.TrackBar.set_Value(Int32 value)
   at MacGen.frmBasicViewer.MG_Player_OnTick(Int32 n) in D:\Dev\Discrim.NET\Discrim.NET\frmBasicViewer.vb:line 1148

   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at MacGen.frmBasicViewer.MG_Player_OnTick(Int32 n) in D:\Dev\Discrim.NET\Discrim.NET\frmBasicViewer.vb:line 1117

   at MacGen.frmQuickViewer.BGW_DoWork(Object sender, DoWorkEventArgs e) in D:\Dev\Discrim.NET\Discrim.NET\frmQuickViewer.vb:line 125
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by Sirvant** [comment]
Apparently this si related to the haas naming style of programs

**Comment by Sirvant** [comment]
also it is havign trouble with M97 P1000
